version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - tutorial-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=album-list
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  tutorial-volume: